### PR TITLE
Drupal 9 deprecation fixes

### LINKED ISSUE #15: Drupal 9 compatibility
Running drupal/upgrade_status report on an installed cwd_events_localist_pull v1.1.5, I get the following issues:

- [ ] cwd_events_localist_pull.module
```
 ------ -------------------------------------------------------------------------- 
  33     Call to deprecated method entityManager() of class Drupal:                
         in drupal:8.0.0 and is removed from drupal:9.0.0.                         
         Use \Drupal::entityTypeManager() instead in most cases. If the needed     
         method is not on \Drupal\Core\Entity\EntityTypeManagerInterface, see the  
         deprecated \Drupal\Core\Entity\EntityManager to find the                  
         correct interface or service.                                             
```

- [ ] src/Form/LocalistDeleteForm.php                                       
```
 ------ ---------------------------------------------------------------------- 
  40     Call to deprecated function drupal_set_message():                     
         in drupal:8.5.0 and is removed from drupal:9.0.0.                     
         Use \Drupal\Core\Messenger\MessengerInterface::addMessage() instead.  
```

- [ ] src/Form/LocalistEntityForm.php                                       
```
 ------ ---------------------------------------------------------------------- 
  302    Call to deprecated function drupal_set_message():                     
         in drupal:8.5.0 and is removed from drupal:9.0.0.                     
         Use \Drupal\Core\Messenger\MessengerInterface::addMessage() instead.  
  307    Call to deprecated function drupal_set_message():                     
         in drupal:8.5.0 and is removed from drupal:9.0.0.                     
         Use \Drupal\Core\Messenger\MessengerInterface::addMessage() instead.  
```
 - [ ] src/LocalistProcessor.php
```
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 
  135    Call to deprecated constant FILE_CREATE_DIRECTORY: Deprecated in drupal:8.7.0 and is removed from drupal:9.0.0. Use \Drupal\Core\File\FileSystemInterface::CREATE_DIRECTORY.  
  135    Call to deprecated function file_prepare_directory():                                                                                                                         
         in drupal:8.7.0 and is removed from drupal:9.0.0.                                                                                                                             
         Use \Drupal\Core\File\FileSystemInterface::prepareDirectory().                                                                                                                
  136    Call to deprecated constant FILE_EXISTS_REPLACE: Deprecated in drupal:8.7.0 and is removed from drupal:9.0.0. Use \Drupal\Core\File\FileSystemInterface::EXISTS_REPLACE.      
```

### PR DESCRIPTION
**Pull request by woodseowl**
Addresses items found using drupal/upgrade_status and reported in #15.

The upgrade_status scan reported no known issues on the module after these updates. While that doesn't guarantee D9 compatibility, it's a good start.

Note: I didn't add an explicit drupal/core ^8.7.7 || ^9.0 composer requirement, but that may be a good idea?

Closes #15.

----
_UPDATE (Alison here)_
**Next steps:**
* [ ] Code review
* [ ] Put drupal9 branch of this module on a CD Demo multidev -- it'll be testing it on a D8 site with an existing install of the module, but still something we need to do:
`composer require cubear/cwd_events_localist_pull:dev-drupal9`
  * Check upgrade status against the issues listed in #15
  * Test module functionality
* [ ] Test on a D9 site (@ssh6 says he'll see if he can help us with this item)

### CODE REVIEW

**Comment by ssh6** [comment]
@alisonjo315 Would be great to get this merged, so I'm not manually overriding my local copy.

**Comment by alisonjo315** [comment]
@ssh6 Gotcha.

You have a site running D9? If yes, could you help us with the third checklist item I just put in the PR description? --
* On a dev env, install the branch of the module associated with this PR:
`composer require cubear/cwd_events_localist_pull:dev-drupal9`
* Give the module a workout, try to find breakage (specifically, new breakage -- idk what issues already exist, but you probably do).
* (Report back)

Is that something you could help with?

Thanks!

**Comment by ssh6** [comment]
@alisonjo315 I'm working on D9, but with multi-site it is complicated.  Module support is one of the blockers.  I'll test this as I can.

**Review by inaydich — APPROVED** [review]
Looks good

**Pull request merged**
