### PR TITLE
entity.query deprecation

### PR DESCRIPTION
**Pull request by alisonjo315**
fixes issue #22

### CODE REVIEW

**Comment by alisonjo315** [comment]
@ssh6 If you have time, could you try updating cwd_events_localist_pull to use the "eq-fix" branch and let us know if it resolves the issue?

(If yes you have time, you can add yourself as a reviewer of this PR and then share the results as a review -- if things look good, I'll merge and publish a new release of the module.)  (If no, that's ok :) )

**Comment by alisonjo315** [comment]
Shoot, hold on, I messed it up!

**Comment by alisonjo315** [comment]
@ssh6 Sorry about that -- for real this time, ready for review -- details in my earlier comment:
https://github.com/CU-CommunityApps/CD_cwd_events_localist_pull/pull/27#issuecomment-885821461

**Comment by ssh6** [comment]
@alisonjo315 Can't add myself as a reviewer.  

No change.  Still have the same error message.  `Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "entity.query". Did you mean one of these: "entity.query.config", "entity.query.sql", "pgsql.entity.query.sql", "entity.query.null", "entity.query.keyvalue"? in Drupal\Component\DependencyInjection\Container->get() (line 156 of /mnt/www/html/cornellssitd9dev/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php).`

**Comment by ssh6** [comment]
`Drupal\Core\Config\Schema\SchemaIncompleteException: Entity type 'Drupal\cwd_events_localist_pull\Entity\LocalistConfig' is missing 'config_export' definition in its annotation in Drupal\Core\Config\Entity\ConfigEntityBase->toArray() (line 252 of /mnt/www/html/cornellssitd9dev/docroot/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php).`

**Comment by alisonjo315** [comment]
@ssh6 Thanks for testing!  (We'll keep the config export issue over here #26 -- but, regarding the entity.query deprecation issue --)

Blerg, the error cleared when I tested on a d9 site over here... Sorry for the silly question but are you certain the module code got updated?  You might need to do `composer clear-cache` before running the composer require command because of my mis-fire the first time I committed the change.

After updating the module from `2.0.0` to the `eq-fix` branch, the diff for `cwd_events_localist_pull.module` should look like this:
```diff
--- a/web/modules/custom/cwd_events_localist_pull/cwd_events_localist_pull.module
+++ b/web/modules/custom/cwd_events_localist_pull/cwd_events_localist_pull.module
@@ -28,7 +28,9 @@ function cwd_events_localist_pull_help($route_name, RouteMatchInterface $route_m
 }
 
 function cwd_events_localist_pull_cron() {
-    $query = \Drupal::service('entity.query')->get('localist_pull');
+    // updating deprecated code
+    // $query = \Drupal::service('entity.query')->get('localist_pull');
+    $query = \Drupal::entityQuery('localist_pull');
     $entity_ids = $query->execute();
     $config_storage = \Drupal::entityTypeManager()->getStorage('localist_pull');
     $configs = $config_storage->loadMultiple($entity_ids);
```

Let me know if that's what you see or not.  Thank you!!

**Comment by ssh6** [comment]
@alisonjo315 you actually wanted me to push the changes to our environment, and not just leave it on my local system?  Oh... 😄 

So now that I've remedied that ... brain hiccup... it is completing without error.

**Comment by alisonjo315** [comment]
haha andYAY!!  I'm gonna merge this thing.  Thank you thank you!

**Pull request merged**
